apiVersion: v1
kind: Pod
metadata:
  name: prometheus-grafana-REVISION_PLACEHOLDER
  labels:
    app: grafana
    revision: REVISION_PLACEHOLDER
spec:
  containers:

  - name: prometheus
    image: prom/prometheus:v2.3.1
    volumeMounts:
      - name: prometheus
        subPath: prometheus.yml
        mountPath: /etc/prometheus/prometheus.yml
    ports:
    # Prometheus export port
    - containerPort: 9090

  - name: grafana
    image: grafana/grafana
    ports:
    # WebUI
    - containerPort: 3000

  volumes:
  - name: prometheus
    configMap:
      name: prometheus-REVISION_PLACEHOLDER

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-REVISION_PLACEHOLDER
  labels:
    app: grafana
    revision: REVISION_PLACEHOLDER
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: grafana
    revision: REVISION_PLACEHOLDER
  type: LoadBalancer
